\c gregs_list

SELECT * FROM my_contacts;

SELECT * FROM my_contacts WHERE first_name = 'Bob';

SELECT birthday FROM my_contacts WHERE first_name = 'Bob';

SELECT * FROM my_contacts
WHERE
  first_name > 'Bob'
AND
  joined >= '1970-01-01 00:00:00';

SELECT note FROM my_contacts
WHERE
  note LIKE '%good music';

SELECT first_name, last_name, age FROM my_contacts
WHERE
  NOT age BETWEEN 50 AND 75;

SELECT note FROM my_contacts
WHERE
  note LIKE '%''%';
